---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r Loading_&_Preprocessing_Data, echo=TRUE}
x <- read.csv("./activity.csv")
```

## What is mean total number of steps taken per day?
```{r Steps_Calcs, echo=TRUE}
agg <- aggregate(x$steps, by=list(Date=x$date), FUN=sum, na.rm=TRUE)
hist(agg$x,xlab="Total Steps Taken per Day",main="Histogram of Total Steps Taken per Day")
mean_steps_byday <- mean(agg$x)
median_steps_byday <- median(agg$x)
mean_steps_byday
median_steps_byday
```

## What is the average daily activity pattern?
```{r Daily_Active_Pattern, echo=TRUE}
agg2 <- aggregate(x$steps,by=list(Interval = x$interval), FUN=mean, na.rm=TRUE)
plot(agg2$Interval, agg2$x, type="l", ylab="Average Step Number", xlab="5-minute Interval",
     main="Average Step Number by 5-minute Interval")

max_interval <- agg2[agg2$x == max(agg2$x),][1,1]
max_interval
```

## Imputing missing values
```{r Missing_Values, echo=TRUE}
require(Hmisc)
NA_values <- sum(is.na(x$steps))
NA_values

# Data is imputed using the impute() function of the Hmisc package.  See ?impute for details.
y <- impute(x$steps, mean)
x_i <- as.data.frame(cbind(y, x$date, x$interval))
names(x_i) <- names(x)
agg3 <- aggregate(x_i$steps, by=list(Date=x_i$date), FUN=sum)
agg3$x <- as.integer(agg3$x)
hist(agg3$x,xlab="Total Steps Taken per Day",main="Histogram of Total Steps Taken per Day\n(Imputed)")
mean_steps_byday_i <- mean(agg3$x)
median_steps_byday_i <- median(agg3$x)
mean_steps_byday_i
median_steps_byday_i
```

## Are there differences in activity patterns between weekdays and weekends?
```{r Weekdays_vs._Weekends, echo=TRUE}
require(ggplot2)
require(dplyr)
x <- mutate(x, weekday = weekdays(as.Date(date, "%Y-%m-%d")))
x$weekday <- factor(x = x$weekday %in% c("Saturday", "Sunday"), levels=c(TRUE,FALSE), labels=c("weekend","weekday"))
agg4 <- aggregate(x$steps, by=list(Interval = x$interval, Day = x$weekday), FUN=mean, na.rm=TRUE)
ggplot(data=agg4, aes(Interval,x)) + geom_line() + facet_grid(agg4$Day ~ .) + 
    labs(x="Interval", y = "Average Number of Steps", title = "Average Step Number by 5-minute Interval")
```
